services:
  localstack:
    container_name: localstack-demo_topicos_filas
    image: localstack/localstack
    hostname: localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SKIP_SSL_CERT_DOWNLOAD=1
      - SERVICES=sns,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=Dumy-99
      - AWS_SECRET_ACCESS_KEY=Dumy-99
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
